version: '3'
services:
  app:
    image: django-app-prod
    build:
      context: ./src
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 backend.backend.wsgi:application
    environment:
      # separate settings file with more restrictive security settings
      - DJANGO_SETTINGS_MODULE=backend.backend.settings_prod
    ports:
      - 8000:8000
    devices:
      - /dev/snd:/dev/snd