version: '3'
services:
  plantuml-server:
    image: plantuml/plantuml-server
    container_name: plantuml-local-server
    ports:
      - 8080:8080
  app:
    image: django-app-dev
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    command: python3 ./backend/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./src:/usr/src/app